import { useEffect, useRef, useState } from "react";
import { generateIdeas, submitFeedback } from "../api/client";
import { GenerateButton } from "../components/GenerateButton";
import { IdeaList } from "../components/IdeaList";
import type { FeedbackRating, IdeaCard } from "../types";

export function Home() {
  const [ideas, setIdeas] = useState<IdeaCard[]>([]);
  const [isBootstrapping, setIsBootstrapping] = useState(false);
  const [error, setError] = useState("");
  const [feedbackState, setFeedbackState] = useState<Record<string, string>>({});
  const hasAutoGenerated = useRef(false);

  useEffect(() => {
    if (hasAutoGenerated.current || ideas.length > 0) {
      return;
    }

    hasAutoGenerated.current = true;

    void (async () => {
      try {
        setIsBootstrapping(true);
        setError("");
        const generated = await generateIdeas({ detailLevel: "standard", count: 3 });
        setIdeas(generated);
      } catch (bootstrapError) {
        setError(
          bootstrapError instanceof Error
            ? bootstrapError.message
            : "初回アイデアの生成に失敗しました。",
        );
      } finally {
        setIsBootstrapping(false);
      }
    })();
  }, [ideas.length]);

  const handleFeedback = async (ideaId: string, rating: FeedbackRating) => {
    try {
      await submitFeedback({ ideaCardId: ideaId, rating });
      setFeedbackState((current) => ({ ...current, [ideaId]: "フィードバックを保存しました。" }));
    } catch (feedbackError) {
      setFeedbackState((current) => ({
        ...current,
        [ideaId]:
          feedbackError instanceof Error ? feedbackError.message : "フィードバック送信に失敗しました。",
      }));
    }
  };

  const feedbackMessages = Object.values(feedbackState);
  const latestFeedback = feedbackMessages[feedbackMessages.length - 1];

  return (
    <div className="space-y-6">
      <GenerateButton onGenerated={setIdeas} onError={setError} />

      {error ? (
        <div className="rounded-2xl border border-rose-500/30 bg-rose-500/10 px-4 py-3 text-sm text-rose-100">
          {error}
        </div>
      ) : null}

      {isBootstrapping ? (
        <div className="rounded-3xl border border-slate-800 bg-slate-900/60 px-6 py-5 text-sm text-slate-300">
          今日の 3 アイデアを生成しています...
        </div>
      ) : null}

      <IdeaList ideas={ideas} onFeedback={handleFeedback} />

      {latestFeedback ? (
        <div className="rounded-3xl border border-slate-800 bg-slate-900/60 p-4 text-sm text-slate-300">
          最新の送信結果: {latestFeedback}
        </div>
      ) : null}
    </div>
  );
}
